# Configuration for the actionlint tool, which we run via prek
# to verify the correctness of the syntax in our GitHub Actions workflows.

self-hosted-runner:
  # Various runners we use that aren't recognized out-of-the-box by actionlint:
  labels:
    - codspeed-macro
