coverage:
  status:
    project:
      default: # default is the status check's name, not default settings
        target: auto
        threshold: "5%"
    patch:
      default:
        enabled: false

ignore:
  - "karva"
  - "karva_benchmark"
  - "karva_cli"
  - "karva_dev"
  - "karva_diff"
  - "karva_test"
