ci:
  - changed-files:
      - any-glob-to-any-file: [".github/**/*"]

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "!docs/cli.md"
          - "mkdocs.yml"
