ci:
  - changed-files:
      - any-glob-to-any-file: [".github/**/*"]

extensions/fixtures:
  - changed-files:
      - any-glob-to-any-file: ["crates/karva_core/src/extensions/fixtures/**/*"]

extensions/tags:
  - changed-files:
      - any-glob-to-any-file: ["crates/karva_core/src/extensions/tags/**/*"]

discovery:
  - changed-files:
      - any-glob-to-any-file:
          [
            "crates/karva_core/src/discovery/**/*",
            "crates/karva_core/src/collection/**/*",
          ]

documentation:
  - changed-files:
      - any-glob-to-any-file: ["docs/**/*", "README.md", "mkdocs.yml"]

cli:
  - changed-files:
      - any-glob-to-any-file: ["crates/karva_cli/**/*"]

reporting:
  - changed-files:
      - any-glob-to-any-file:
          [
            "crates/karva_core/src/diagnostic/**/*",
            "crates/karva_core/src/runner/diagnostic.rs",
          ]

performance:
  - changed-files:
      - any-glob-to-any-file: ["crates/karva_benchmark/**/*"]

testing:
  - changed-files:
      - any-glob-to-any-file: ["crates/karva_test/**/*"]
