ci:
  - changed-files:
      - any-glob-to-any-file: [".github/**/*"]

documentation:
  - changed-files:
      - any-glob-to-any-file: ["docs/**/*", "mkdocs.yml"]
      - all-globs-to-all-files: ["!docs/cli.md"]
