name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
template: |
  ## Release Notes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

change-template: "- $TITLE @$AUTHOR ([#$NUMBER](https://github.com/MatthewMckee4/karva/pull/$NUMBER))"

categories:
  - title: Breaking
    label: breaking
  - title: New
    labels:
      - feature
      - enhancement
  - title: Bug Fixes
    label: bug
  - title: Documentation
    label: documentation
  - title: Other changes

version-resolver:
  default: patch
