name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
template: |
  ## Release Notes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

change-template: "- $TITLE @$AUTHOR ([#$NUMBER](https://github.com/MatthewMckee4/karva/pull/$NUMBER))"

categories:
  - title: Bug Fixes
    label: bug
  - title: Reporting
    label: reporting
  - title: Extensions
    labels:
      - "extensions/fixtures"
      - "extensions/tags"
  - title: Discovery
    label: discovery
  - title: CLI
    label: cli
  - title: Documentation
    label: documentation

version-resolver:
  default: patch

exclude-contributors:
  - dependabot
  - dependabot[bot]

exclude-labels:
  - dependencies
  - testing
  - rust
  - question
  - performance
  - contributor-friendly
