[build-system]
build-backend = "maturin"
requires = ["maturin>=1.9.3,<2.0"]

[project]
name = "karva"
version = "0.0.1-alpha.9"
description = "A Python test framework, written in Rust."
authors = [{ name = "Matthew Mckee", email = "matthewmckee04@yahoo.co.uk" }]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.10,<3.15"
keywords = ["karva", "pytest", "rust", "testing"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Rust",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Testing",
]

[project.scripts]
karva = "karva._karva:karva_run"
karva-worker = "karva._karva:karva_worker_run"

[dependency-groups]
dev = [
    "ruff>=0.16.1",
    "ty>=0.0.65",
]
docs = ["zensical==0.0.51"]

[project.urls]
Changelog = "https://github.com/MatthewMckee4/karva/blob/main/CHANGELOG.md"
Documentation = "https://matthewmckee4.github.io/karva/"
Homepage = "https://matthewmckee4.github.io/karva/"
Issues = "https://github.com/MatthewMckee4/karva/issues"
Repository = "https://github.com/MatthewMckee4/karva"

[tool.maturin]
manifest-path = "crates/karva_python/Cargo.toml"
module-name = "karva._karva"
python-source = "python"
features = ["pyo3/extension-module"]
strip = true

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "Cargo.toml" },
    { file = "Cargo.lock" },
    { file = ".cargo/config.toml" },
    { file = "rust-toolchain.toml" },
    { file = "crates/**/*.rs" },
    { file = "crates/**/Cargo.toml" },
]

[tool.ruff]
extension = { pyi = "python" }
fix = true
target-version = "py311"

[tool.ruff.lint]
exclude = [
    "python/karva/_vendor/**/*.py",
]
select = ["ALL"]
ignore = [
    "D100",
    "CPY001",
    "EM101"
]

# [tool.ruff.lint.per-file-ignores]
# "crates/karva/tests/projects/wheel-smoke/tests/*.py" = [
#     "ANN001",
#     "D103",
#     "INP001",
#     "S101",
# ]

[tool.ty.environment]
python-version = "3.11"

[tool.ty.src]
include = ["python"]
