[package]
name = "karva_python"
version = "0.0.1"
publish = false

edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lib]
name = "_karva"
crate-type = ["cdylib"]

[dependencies]
karva_core = { workspace = true }

pyo3 = { workspace = true }
