name: Question
description: Ask a question about Karva
labels: ["question"]
body:
  - type: textarea
    attributes:
      label: Question
      description: Describe your question in detail.
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: What version of Karva are you using? (see `karva --version`)
      placeholder: e.g., Karva 0.1.0
    validations:
      required: false
