use std::num::{NonZeroUsize, ParseIntError};
use std::{env, fmt, io};

/// Documentation metadata for a single environment variable. Generated by the
/// [`env_vars!`] macro and consumed by `karva_dev` to build `docs/env-vars.md`.
pub struct EnvVarDoc {
    pub name: &'static str,
    /// Raw doc-comment lines as written above the constant. Each entry includes
    /// the leading space rustc captures from `///` (consumers should trim it).
    pub doc_lines: &'static [&'static str],
}

/// Defines a unit struct of `&'static str` environment-variable name constants
/// and exposes a `METADATA: &'static [EnvVarDoc]` slice next to it for
/// documentation generation.
macro_rules! env_vars {
    (
        $(#[doc = $struct_doc:literal])*
        $vis:vis struct $struct:ident {
            $(
                $(#[doc = $doc:literal])*
                pub const $name:ident: &'static str = $value:literal;
            )*
        }
    ) => {
        $(#[doc = $struct_doc])*
        $vis struct $struct;

        impl $struct {
            $(
                $(#[doc = $doc])*
                pub const $name: &'static str = $value;
            )*

            /// Documentation metadata for every variable on this struct, in
            /// declaration order.
            pub const METADATA: &'static [$crate::EnvVarDoc] = &[
                $(
                    $crate::EnvVarDoc {
                        name: $value,
                        doc_lines: &[$($doc),*],
                    },
                )*
            ];
        }
    };
}

env_vars! {
    /// Environment variables that Karva itself reads from the environment.
    pub struct EnvVars {
        /// This is a standard Rayon environment variable.
        pub const RAYON_NUM_THREADS: &'static str = "RAYON_NUM_THREADS";

        /// This is a standard Karva environment variable.
        pub const KARVA_MAX_PARALLELISM: &'static str = "KARVA_MAX_PARALLELISM";

        /// This is a standard Karva environment variable.
        pub const KARVA_CONFIG_FILE: &'static str = "KARVA_CONFIG_FILE";

        /// Configuration profile to use, equivalent to `--profile`.
        pub const KARVA_PROFILE: &'static str = "KARVA_PROFILE";

        /// Behavior when no tests are found to run, equivalent to
        /// `--no-tests`.
        pub const KARVA_NO_TESTS: &'static str = "KARVA_NO_TESTS";

        /// Test result statuses to display during the run, equivalent to
        /// `--status-level`.
        pub const KARVA_STATUS_LEVEL: &'static str = "KARVA_STATUS_LEVEL";

        /// Test summary information to display at the end of the run,
        /// equivalent to `--final-status-level`.
        pub const KARVA_FINAL_STATUS_LEVEL: &'static str = "KARVA_FINAL_STATUS_LEVEL";

        /// When set to a truthy boolish value, snapshot assertions write
        /// directly to `.snap` instead of creating `.snap.new` pending files.
        pub const KARVA_SNAPSHOT_UPDATE: &'static str = "KARVA_SNAPSHOT_UPDATE";

        /// When set to a truthy boolish value, writes tracing profile output
        /// to `tracing.folded`.
        pub const KARVA_LOG_PROFILE: &'static str = "KARVA_LOG_PROFILE";

        /// Path to the active Python virtual environment. Used as a fallback
        /// when resolving the `karva-worker` binary.
        pub const VIRTUAL_ENV: &'static str = "VIRTUAL_ENV";
    }
}

/// Environment variables read by Karva's developer and benchmark tooling.
pub struct ToolEnvVars;

impl ToolEnvVars {
    /// The cargo executable to use for cargo subcommands.
    pub const CARGO: &'static str = "CARGO";

    /// The cargo target directory to use for build artifacts.
    pub const CARGO_TARGET_DIR: &'static str = "CARGO_TARGET_DIR";

    /// The standard executable search path environment variable.
    pub const PATH: &'static str = "PATH";

    /// Python version to use when creating integration-test virtual
    /// environments.
    pub const PYTHON_VERSION: &'static str = "PYTHON_VERSION";
}

/// Environment variables used when invoking Python processes.
pub struct PythonEnvVars;

impl PythonEnvVars {
    /// Forces unbuffered I/O streams, equivalent to `python -u`.
    pub const PYTHONUNBUFFERED: &'static str = "PYTHONUNBUFFERED";
}

env_vars! {
    /// Environment variables that the Karva worker sets on the test process so
    /// running tests can read them at runtime.
    pub struct WorkerEnvVars {
        /// Always set to `"1"`. The cheapest signal that test code is running
        /// under Karva, useful for fixtures and helpers that want to detect
        /// the runner without heavier introspection.
        pub const KARVA: &'static str = "KARVA";

        /// 0-indexed worker number. The canonical way to partition shared
        /// resources (database names, ports, scratch directories) across
        /// parallel workers without coordination.
        pub const KARVA_WORKER_ID: &'static str = "KARVA_WORKER_ID";

        /// Unique identifier for a single `karva test` invocation, shared by
        /// every worker. Encodes `<ms>-<uuid>`: a millisecond Unix timestamp
        /// followed by a UUID v4. The timestamp prefix sorts chronologically
        /// across runs; the UUID makes the id unique even when multiple jobs
        /// start in the same millisecond. The same value names the run's
        /// cache directory under `.karva_cache/run-<ms>-<uuid>`, which makes
        /// correlating logs to cached artifacts straightforward.
        pub const KARVA_RUN_ID: &'static str = "KARVA_RUN_ID";

        /// Absolute path to the directory Karva resolved as the project root.
        /// Saves tests from re-deriving the root via `__file__` walking or
        /// `os.getcwd()` heuristics.
        pub const KARVA_WORKSPACE_ROOT: &'static str = "KARVA_WORKSPACE_ROOT";

        /// Qualified name of the currently running test, e.g.
        /// `pkg.module::test_foo(value=1)`. Updated before each attempt.
        pub const KARVA_TEST_NAME: &'static str = "KARVA_TEST_NAME";

        /// The 1-indexed attempt number for the currently running test. Always
        /// set; `"1"` when no retries are configured.
        pub const KARVA_ATTEMPT: &'static str = "KARVA_ATTEMPT";

        /// The total number of attempts allowed for the currently running test
        /// (`retries + 1`). Always set.
        pub const KARVA_TOTAL_ATTEMPTS: &'static str = "KARVA_TOTAL_ATTEMPTS";

        /// Name of the active configuration profile, e.g. `"default"` or
        /// whatever was passed to `--profile` / `KARVA_PROFILE`.
        pub const KARVA_PROFILE: &'static str = "KARVA_PROFILE";

        /// Configured number of worker processes for this run. Mirrors
        /// `--num-workers` (capped to the number of useful workers).
        pub const KARVA_TEST_THREADS: &'static str = "KARVA_TEST_THREADS";

        /// Version of the running karva CLI.
        pub const KARVA_VERSION: &'static str = "KARVA_VERSION";
    }
}

#[derive(Debug)]
pub enum MaxParallelismError {
    InvalidValue {
        name: &'static str,
        value: String,
        source: ParseIntError,
    },
    InvalidUnicode {
        name: &'static str,
    },
    AvailableParallelism(io::Error),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BoolishEnvVarError {
    InvalidValue { name: &'static str, value: String },
    InvalidUnicode { name: &'static str, value: String },
}

impl fmt::Display for BoolishEnvVarError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidValue { name, value } => {
                write!(
                    f,
                    "invalid {name} value `{value}`; expected a boolish value"
                )
            }
            Self::InvalidUnicode { name, value } => {
                write!(f, "{name} must contain valid Unicode, got `{value}`")
            }
        }
    }
}

impl std::error::Error for BoolishEnvVarError {}

impl fmt::Display for MaxParallelismError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidValue { name, value, .. } => {
                write!(
                    f,
                    "invalid {name} value `{value}`; expected a positive integer"
                )
            }
            Self::InvalidUnicode { name } => {
                write!(f, "{name} must contain valid Unicode")
            }
            Self::AvailableParallelism(err) => {
                write!(f, "failed to determine available parallelism: {err}")
            }
        }
    }
}

impl std::error::Error for MaxParallelismError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::InvalidValue { source, .. } => Some(source),
            Self::InvalidUnicode { .. } => None,
            Self::AvailableParallelism(source) => Some(source),
        }
    }
}

pub fn parse_boolish_env_var(name: &'static str) -> Result<Option<bool>, BoolishEnvVarError> {
    match env::var(name) {
        Ok(value) => parse_boolish(&value)
            .map(Some)
            .ok_or(BoolishEnvVarError::InvalidValue { name, value }),
        Err(env::VarError::NotPresent) => Ok(None),
        Err(env::VarError::NotUnicode(value)) => Err(BoolishEnvVarError::InvalidUnicode {
            name,
            value: value.to_string_lossy().into_owned(),
        }),
    }
}

fn parse_boolish(value: &str) -> Option<bool> {
    const TRUE_LITERALS: &[&str] = &["y", "yes", "t", "true", "on", "1"];
    const FALSE_LITERALS: &[&str] = &["n", "no", "f", "false", "off", "0"];

    if TRUE_LITERALS
        .iter()
        .any(|literal| value.eq_ignore_ascii_case(literal))
    {
        Some(true)
    } else if FALSE_LITERALS
        .iter()
        .any(|literal| value.eq_ignore_ascii_case(literal))
    {
        Some(false)
    } else {
        None
    }
}

pub fn max_parallelism() -> Result<NonZeroUsize, MaxParallelismError> {
    if let Some(parallelism) = configured_parallelism(EnvVars::KARVA_MAX_PARALLELISM)? {
        return Ok(parallelism);
    }
    if let Some(parallelism) = configured_parallelism(EnvVars::RAYON_NUM_THREADS)? {
        return Ok(parallelism);
    }

    std::thread::available_parallelism().map_err(MaxParallelismError::AvailableParallelism)
}

fn configured_parallelism(name: &'static str) -> Result<Option<NonZeroUsize>, MaxParallelismError> {
    match env::var(name) {
        Ok(value) => value
            .parse()
            .map(Some)
            .map_err(|source| MaxParallelismError::InvalidValue {
                name,
                value,
                source,
            }),
        Err(env::VarError::NotPresent) => Ok(None),
        Err(env::VarError::NotUnicode(_)) => Err(MaxParallelismError::InvalidUnicode { name }),
    }
}

#[cfg(test)]
mod tests {
    use std::ffi::OsString;
    use std::sync::{Mutex, MutexGuard};

    use super::{
        BoolishEnvVarError, EnvVars, MaxParallelismError, max_parallelism, parse_boolish_env_var,
    };

    static ENV_LOCK: Mutex<()> = Mutex::new(());

    struct EnvRestore {
        values: Vec<(&'static str, Option<OsString>)>,
        _guard: MutexGuard<'static, ()>,
    }

    impl EnvRestore {
        fn new() -> Self {
            let guard = ENV_LOCK.lock().expect("env lock");
            let names = [
                EnvVars::KARVA_MAX_PARALLELISM,
                EnvVars::RAYON_NUM_THREADS,
                EnvVars::KARVA_LOG_PROFILE,
                EnvVars::KARVA_SNAPSHOT_UPDATE,
            ];
            Self {
                values: names
                    .into_iter()
                    .map(|name| (name, std::env::var_os(name)))
                    .collect(),
                _guard: guard,
            }
        }

        fn set(name: &str, value: &str) {
            // SAFETY: Tests in this module hold ENV_LOCK while mutating env vars.
            unsafe {
                std::env::set_var(name, value);
            }
        }

        fn remove(name: &str) {
            // SAFETY: Tests in this module hold ENV_LOCK while mutating env vars.
            unsafe {
                std::env::remove_var(name);
            }
        }
    }

    impl Drop for EnvRestore {
        fn drop(&mut self) {
            for (name, value) in &self.values {
                match value {
                    Some(value) => {
                        // SAFETY: Tests in this module hold ENV_LOCK while mutating env vars.
                        unsafe {
                            std::env::set_var(name, value);
                        }
                    }
                    None => {
                        // SAFETY: Tests in this module hold ENV_LOCK while mutating env vars.
                        unsafe {
                            std::env::remove_var(name);
                        }
                    }
                }
            }
        }
    }

    #[test]
    fn max_parallelism_prefers_karva_env_var() {
        let _restore = EnvRestore::new();
        EnvRestore::set(EnvVars::KARVA_MAX_PARALLELISM, "3");
        EnvRestore::set(EnvVars::RAYON_NUM_THREADS, "2");

        assert_eq!(max_parallelism().expect("parallelism").get(), 3);
    }

    #[test]
    fn max_parallelism_uses_rayon_when_karva_env_var_is_absent() {
        let _restore = EnvRestore::new();
        EnvRestore::remove(EnvVars::KARVA_MAX_PARALLELISM);
        EnvRestore::set(EnvVars::RAYON_NUM_THREADS, "2");

        assert_eq!(max_parallelism().expect("parallelism").get(), 2);
    }

    #[test]
    fn max_parallelism_rejects_invalid_env_var() {
        let _restore = EnvRestore::new();
        EnvRestore::set(EnvVars::KARVA_MAX_PARALLELISM, "0");
        EnvRestore::remove(EnvVars::RAYON_NUM_THREADS);

        let Err(MaxParallelismError::InvalidValue { name, value, .. }) = max_parallelism() else {
            panic!("expected invalid parallelism");
        };
        assert_eq!(name, EnvVars::KARVA_MAX_PARALLELISM);
        assert_eq!(value, "0");
    }

    #[test]
    fn boolish_env_var_accepts_true_values() {
        let _restore = EnvRestore::new();

        for value in ["1", "true", "TRUE", "yes", "on", "t", "y"] {
            EnvRestore::set(EnvVars::KARVA_SNAPSHOT_UPDATE, value);
            assert_eq!(
                parse_boolish_env_var(EnvVars::KARVA_SNAPSHOT_UPDATE).expect("boolish"),
                Some(true)
            );
        }
    }

    #[test]
    fn boolish_env_var_accepts_false_values() {
        let _restore = EnvRestore::new();

        for value in ["0", "false", "FALSE", "no", "off", "f", "n"] {
            EnvRestore::set(EnvVars::KARVA_LOG_PROFILE, value);
            assert_eq!(
                parse_boolish_env_var(EnvVars::KARVA_LOG_PROFILE).expect("boolish"),
                Some(false)
            );
        }
    }

    #[test]
    fn boolish_env_var_rejects_invalid_value() {
        let _restore = EnvRestore::new();
        EnvRestore::set(EnvVars::KARVA_LOG_PROFILE, "sometimes");

        assert_eq!(
            parse_boolish_env_var(EnvVars::KARVA_LOG_PROFILE),
            Err(BoolishEnvVarError::InvalidValue {
                name: EnvVars::KARVA_LOG_PROFILE,
                value: "sometimes".to_string(),
            })
        );
    }
}
