[package]
name = "karva_python_semantic"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
description = "Python version detection and AST-level semantic types for Karva."
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []
python-runtime = ["dep:pyo3"]
source-analysis = [
    "dep:ruff_db",
    "dep:ruff_ranged_value",
    "dep:ty_project",
    "dep:ty_python_core",
    "dep:ty_python_semantic",
]

[dependencies]
camino = { workspace = true }
pyo3 = { workspace = true, optional = true }
ruff_python_ast = { workspace = true }
ruff_text_size = { workspace = true }
serde = { workspace = true }

ruff_db = { workspace = true, optional = true }
ruff_ranged_value = { workspace = true, optional = true }
ty_project = { workspace = true, optional = true }
ty_python_core = { workspace = true, optional = true }
ty_python_semantic = { workspace = true, optional = true }

[dev-dependencies]
ruff_python_parser = { workspace = true }

[lints]
workspace = true
